[package]
name = "hello-rust"
version = "0.1.0"
authors = ["Edison Gustavo Muenz <edisongustavo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
velcro = "0.5.3"
